<a href="https://colab.research.google.com/github/audirisper/kamilimu_assignments/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')


# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

In [ ]:
# Query to count the total number of medals won by each country.
# Filters out rows where Medal is NULL, groups by NOC (country code),and shows the top 5 countries by total medal count.
pd.read_sql(
    """
    SELECT NOC,
    COUNT(*) AS Total_medals
    FROM athletes_table
    WHERE Medal IS NOT NULL
    GROUP BY NOC
    ORDER BY Total_medals DESC
    LIMIT 5;
    """,
    conn
 )

   NOC  Total_medals
0  USA          5637
1  URS          2503
2  GER          2165
3  GBR          2068
4  FRA          1777

In [ ]:
# Query to calculate the average age of athletes who received a Gold medal.
# Filters rows to only include Gold medalists and computes the average of the Age column.
pd.read_sql(
    """
    SELECT avg(Age)
    FROM athletes_table
    WHERE Medal = 'Gold';
    """,
    conn
)

    avg(Age)
0  25.901013

In [ ]:
# Query to count how many distinct events exist for each sport.
# Uses GROUP BY on Sport and counts DISTINCT Event values.
pd.read_sql(
    """
    SELECT Sport,
    COUNT(DISTINCT Event) AS Total_Distinct_Events
    FROM athletes_table
    GROUP BY Sport
    ORDER BY Total_Distinct_Events DESC;
    """,
    conn
)

            Sport  Total_Distinct_Events
0        Shooting                     83
1       Athletics                     83
2        Swimming                     55
3         Cycling                     44
4         Sailing                     38
..            ...                    ...
61        Cricket                      1
62  Basque Pelota                      1
63       Baseball                      1
64       Alpinism                      1
65    Aeronautics                      1

[66 rows x 2 columns]

In [ ]:
# Query to retrieve all athlete records where the country code (NOC) is 'USA', indicating that the athlete represents the United States.
pd.read_sql(
    """
    SELECT * FROM athletes_table
    WHERE NOC = 'USA';
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,None
1,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,None
2,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,None
3,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
4,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18848,135458,Rami Zur,M,27.0,175.0,77.0,United States,USA,2004 Summer,2004,Summer,Athina,Canoeing,"Canoeing Men's Kayak Doubles, 500 metres",None
18849,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",None
18850,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",None
18851,135543,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States,USA,1964 Summer,1964,Summer,Tokyo,Athletics,"Athletics Men's 3,000 metres Steeplechase",None
18852,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,None

In [ ]:
# Query to count the number of medals awarded in each Olympic year.
# Filters out rows where Medal is NULL and groups the results by Year.

pd.read_sql(
    """
    SELECT Year,
    COUNT(*) AS Total_medals
    FROM athletes_table
    WHERE Medal IS NOT NULL
    GROUP BY Year
    ORDER BY Total_medals DESC;
    """,
    conn
)

    Year  Total_medals
0   2008          2048
1   1992          2030
2   2016          2023
3   2000          2004
4   2004          2001
5   2012          1941
6   1988          1845
7   1996          1842
8   1984          1698
9   1980          1602
10  1976          1531
11  1972          1414
12  1920          1308
13  1968          1256
14  1964          1215
15  1960          1058
16  1956          1043
17  1952          1033
18  1936          1025
19  1948           987
20  1924           962
21  1912           941
22  1908           831
23  1928           823
24  1932           739
25  1900           604
26  2014           597
27  2006           526
28  2010           520
29  1904           486
30  2002           478
31  1906           458
32  1998           440
33  1994           331
34  1896           143

In [ ]:
# Query to identify athlete records where either height or weight is NULL. This helps in cleaning or imputing missing physical data.
pd.read_sql(
    """
    SELECT * FROM athletes_table
    WHERE Height IS NULL OR Weight IS NULL;
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
1,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,None
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,None
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64258,135539,Marius Edmund Zwiller,M,18.0,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,None
64259,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,None
64260,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
64261,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",None
64262,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,None

In [8]:
# Query to update missing height values in the athletes table.
# Calculates the average height from non-null records and sets it as the value for any record where height is currently NULL.
cursor = conn.cursor()

cursor.execute("""
    WITH AvgHeight AS (
        SELECT AVG(height) AS avg_height
        FROM athletes_table
        WHERE height IS NOT NULL
    )
    UPDATE athletes_table
    SET height = (SELECT avg_height FROM AvgHeight)
    WHERE height IS NULL;
""")

# Commit the changes
conn.commit()
# Query to verify the update
pd.read_sql("SELECT * FROM athletes_table WHERE height IS  NOT NULL", conn)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.00000,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None
1,2,A Lamusi,M,23.0,170.00000,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None
2,3,Gunnar Nielsen Aaby,M,24.0,175.33897,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
3,4,Edgar Lindenau Aabye,M,34.0,175.33897,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.00000,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.00000,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,None
271112,135570,Piotr ya,M,27.0,176.00000,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",None
271113,135570,Piotr ya,M,27.0,176.00000,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",None
271114,135571,Tomasz Ireneusz ya,M,30.0,185.00000,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,None
271115,135571,Tomasz Ireneusz ya,M,34.0,185.00000,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,None

In [ ]:
# Query to calculate the total sales for each item.
# It removes the dollar sign from item_price using REPLACE and casts it as a numeric type.Then multiplies it by quantity and groups by item_name.
pd.read_sql(
    """
    SELECT item_name,
    SUM(CAST(REPLACE(item_price, '$', '') AS DECIMAL(10,2)) * quantity) AS total_sales
    FROM sales_table
    GROUP BY item_name
    ORDER BY total_sales DESC;
    """,
    conn
)

                                item_name  total_sales
0                            Chicken Bowl      8044.63
1                         Chicken Burrito      6387.06
2                           Steak Burrito      4236.13
3                              Steak Bowl      2479.81
4                     Chips and Guacamole      2475.62
5                      Chicken Salad Bowl      1506.25
6                      Chicken Soft Tacos      1199.01
7            Chips and Fresh Tomato Salsa      1033.96
8                          Veggie Burrito      1002.27
9                             Veggie Bowl       901.95
10                       Barbacoa Burrito       894.75
11                          Carnitas Bowl       830.71
12                          Barbacoa Bowl       672.36
13                          Bottled Water       649.18
14                       Carnitas Burrito       616.33
15                      Canned Soft Drink       603.75
16                                  Chips       580.34
17                       Steak Soft Tacos       554.55
18                   Chicken Crispy Tacos       524.11
19                       Steak Salad Bowl       391.15
20                    Carnitas Soft Tacos       375.94
21                     Steak Crispy Tacos       375.32
22                      6 Pack Soft Drink       369.93
23                          Side of Chips       290.68
24                    Barbacoa Soft Tacos       250.46
25                            Canned Soda       191.84
26                      Veggie Salad Bowl       182.50
27    Chips and Tomatillo Red Chili Salsa       159.30
28  Chips and Tomatillo Green Chili Salsa       144.55
29                  Barbacoa Crispy Tacos       138.71
30                       Nantucket Nectar       111.87
31                    Barbacoa Salad Bowl       106.40
32                  Carnitas Crispy Tacos        95.94
33    Chips and Tomatillo-Red Chili Salsa        93.21
34                      Veggie Soft Tacos        90.94
35  Chips and Tomatillo-Green Chili Salsa        88.43
36                          Chicken Salad        81.09
37                                   Bowl        74.00
38     Chips and Roasted Chili Corn Salsa        73.75
39                                   Izze        67.80
40                    Carnitas Salad Bowl        66.34
41                           Veggie Salad        50.94
42                                Burrito        44.40
43     Chips and Roasted Chili-Corn Salsa        43.02
44                            Steak Salad        35.66
45                                  Salad        14.80
46                           Crispy Tacos        14.80
47                         Carnitas Salad         8.99
48                    Veggie Crispy Tacos         8.49
49      Chips and Mild Fresh Tomato Salsa         3.00

In [ ]:
# Query to return the top 5 most expensive individual items.
# Casts item_price to a numeric format after removing the dollar sign,orders results in descending order, and limits the output to 5 rows.
pd.read_sql(
    """
    SELECT Item_name,
    CAST(REPLACE(item_price, '$', '') AS REAL) AS item_price
    FROM sales_table
    ORDER BY item_price DESC
    LIMIT 5;
    """,
    conn
)

                      item_name  item_price
0  Chips and Fresh Tomato Salsa       44.25
1                 Carnitas Bowl       35.25
2               Chicken Burrito       35.00
3               Chicken Burrito       35.00
4                Veggie Burrito       33.75

In [ ]:
# This query calculates the total number of unique customer orders by counting the distinct values in the order_id column.
pd.read_sql(
    """
    SELECT COUNT(DISTINCT order_id) AS unique_orders
    FROM sales_table
    """,
    conn
)

   unique_orders
0           1834

In [ ]:
# Query to filter medal-winning athletes and group by country
pd.read_sql(
    """
    WITH medalists_per_country AS (
    SELECT
        NOC,
        COUNT(DISTINCT name) AS medalist_count,
        AVG(age) AS avg_age
    FROM
        athletes_table
    WHERE
        medal IS NOT NULL
        AND age IS NOT NULL
    GROUP BY
        NOC
)
SELECT
    NOC,
    medalist_count,
    ROUND(avg_age, 2) AS average_age,

    -- Classify performance using CASE
    CASE
        WHEN avg_age < 25 THEN 'High'
        WHEN avg_age BETWEEN 25 AND 30 THEN 'Medium'
        ELSE 'Low'
    END AS performance

FROM
    medalists_per_country
ORDER BY
    medalist_count DESC;

    """,
    conn
)

     NOC  medalist_count  average_age performance
0    USA            3795        24.90        High
1    URS            1675        25.27      Medium
2    GBR            1503        27.85      Medium
3    GER            1492        26.42      Medium
4    FRA            1201        27.98      Medium
..   ...             ...          ...         ...
142  SUD               1        23.00        High
143  SUR               1        22.00        High
144  TGA               1        26.00      Medium
145  TOG               1        27.00      Medium
146  ZAM               1        27.00      Medium

[147 rows x 4 columns]